### ISSUE TITLE
ProjectApi: getProjectGoals() is missing

### ISSUE THREAD

**Issue by melloware** [ksmpartners/domino-java-client#34]
5.9.1.0 it seems getProjectGoals is missing.

![image](https://github.com/ksmpartners/domino-java-client/assets/4399574/e7c869b3-d10f-4c52-8a1b-28f28fefe090)

**Comment by kjhoerr** [comment]
Based on the Swagger UI it looks like it got retagged, I'll push up a fix in a bit
